### ISSUE TITLE
Lift doesn't work properly with default arguments

### ISSUE THREAD

**Issue by rikutiira** [calmm-js/kefir.combines#3]
Example:

`U.lift((value = 'bar') => console.log(value) || value)(Kefir.constant('foo'))`

Lifted function logs observable instead of the unboxed value. From quick glance of the source code, I think the cause is checking `function.length` inside lift function, it seems to only count the parameters which are before the first parameter with default arguments.

Not sure if anything can be done about this though, but it was a cause for funny bug in our code.

Maybe a warning if arguments.length and fn.length don't match?

**Comment by polytypic** [comment]
`U.lift` returns a curried function and currently needs to be given a function with a fixed arity (default arguments make functions variable arity).  Also, giving warnings is difficult&mdash;at least in the general case, because it is not uncommon in JS to apply functions to extra arguments.  One option would be to add explicit support for lifting functions with more complex arities.  In some similar cases where you want defaults, you could perhaps use an object of arguments, e.g. `U.lift(({value = 'foo'}) => ...)`, instead.

**Comment by rikutiira** [comment]
Closing this as it's old ticket and I don't think any action needs to be taken specifcally for this.

Maybe a version of `lift` without currying would be useful for working with default arguments. I have noticed myself using a pattern of `fn = (arg1, arg2 = 'default') => K(arg1, arg2, () => ...)` when I need to do this.
